### ISSUE TITLE
Can't install / is docker image available?

### ISSUE THREAD

**Issue by ocstringham** [WFSRDataScience/PIMENTA#1]
I'm trying to install on linux using `bash install.sh` and I get the following error:

> The following packages are incompatible
> ├─ krona does not exist (perhaps a typo or a missing channel);
> └─ taxopy does not exist (perhaps a typo or a missing channel).
> bash: ktUpdateTaxonomy.sh: command not found
> install.sh: line 30: cd: scripts/Porechop/: No such file or directory
> make: *** No targets specified and no makefile found.  Stop.

Do you have a docker image/Dockerfile to run PIMENTA in a container?

<details>
<summary>Full output here</summary>

> (base) [olivers@annotate2 PIMENTA]$ bash install.sh
> Retrieving notices: ...working... done
> Channels:
>  - conda-forge
>  - defaults
> Platform: linux-64
> Collecting package metadata (repodata.json): done
> Solving environment: done
> 
> ## Package Plan ##
> 
>   environment location: /local/home/olivers/miniconda3
> 
>   added / updated specs:
>     - mamba
> 
> 
> The following packages will be downloaded:
> 
>     package                    |            build
>     ---------------------------|-----------------
>     ca-certificates-2024.2.2   |       hbcca054_0         152 KB  conda-forge
>     certifi-2024.2.2           |     pyhd8ed1ab_0         157 KB  conda-forge
>     conda-23.11.0              |  py311h38be061_1         1.2 MB  conda-forge
>     fmt-10.2.1                 |       h00ab1b0_0         189 KB  conda-forge
>     icu-73.2                   |       h59595ed_0        11.5 MB  conda-forge
>     libarchive-3.7.2           |       h2aa1ff5_1         846 KB  conda-forge
>     libcurl-8.5.0              |       h251f7ec_0         416 KB
>     libmamba-1.5.6             |       had39da4_0         1.6 MB  conda-forge
>     libmambapy-1.5.6           |  py311hf2555c7_0         297 KB  conda-forge
>     libxml2-2.12.5             |       h232c23b_0         688 KB  conda-forge
>     lzo-2.10                   |    h516909a_1000         314 KB  conda-forge
>     mamba-1.5.6                |  py311h3072747_0          65 KB  conda-forge
>     openssl-3.2.1              |       hd590300_0         2.7 MB  conda-forge
>     python_abi-3.11            |          2_cp311           5 KB  conda-forge
>     ------------------------------------------------------------
>                                            Total:        20.1 MB
> 
> The following NEW packages will be INSTALLED:
> 
>   libiconv           conda-forge/linux-64::libiconv-1.17-hd590300_2
>   libzlib            conda-forge/linux-64::libzlib-1.2.13-hd590300_5
>   lzo                conda-forge/linux-64::lzo-2.10-h516909a_1000
>   mamba              conda-forge/linux-64::mamba-1.5.6-py311h3072747_0
>   python_abi         conda-forge/linux-64::python_abi-3.11-2_cp311
> 
> The following packages will be UPDATED:
> 
>   ca-certificates    pkgs/main::ca-certificates-2023.12.12~ --> conda-forge::ca-certificates-2024.2.2-hbcca054_0
>   certifi            pkgs/main/linux-64::certifi-2023.11.1~ --> conda-forge/noarch::certifi-2024.2.2-pyhd8ed1ab_0
>   conda              pkgs/main::conda-23.11.0-py311h06a430~ --> conda-forge::conda-23.11.0-py311h38be061_1
>   fmt                       pkgs/main::fmt-9.1.0-hdb19cb5_0 --> conda-forge::fmt-10.2.1-h00ab1b0_0
>   icu                        pkgs/main::icu-73.1-h6a678d5_0 --> conda-forge::icu-73.2-h59595ed_0
>   libarchive         pkgs/main::libarchive-3.6.2-h6ac8c49_2 --> conda-forge::libarchive-3.7.2-h2aa1ff5_1
>   libcurl                                  8.4.0-h251f7ec_1 --> 8.5.0-h251f7ec_0
>   libgcc-ng          pkgs/main::libgcc-ng-11.2.0-h1234567_1 --> conda-forge::libgcc-ng-13.2.0-h807b86a_5
>   libgomp              pkgs/main::libgomp-11.2.0-h1234567_1 --> conda-forge::libgomp-13.2.0-h807b86a_5
>   libmamba             pkgs/main::libmamba-1.5.3-haf1ee3a_0 --> conda-forge::libmamba-1.5.6-had39da4_0
>   libmambapy         pkgs/main::libmambapy-1.5.3-py311h2da~ --> conda-forge::libmambapy-1.5.6-py311hf2555c7_0
>   libstdcxx-ng       pkgs/main::libstdcxx-ng-11.2.0-h12345~ --> conda-forge::libstdcxx-ng-13.2.0-h7e041cc_5
>   libxml2              pkgs/main::libxml2-2.10.4-hf1b16e4_1 --> conda-forge::libxml2-2.12.5-h232c23b_0
>   openssl              pkgs/main::openssl-3.0.12-h7f8727e_0 --> conda-forge::openssl-3.2.1-hd590300_0
>   zlib                    pkgs/main::zlib-1.2.13-h5eee18b_0 --> conda-forge::zlib-1.2.13-hd590300_5
> 
> The following packages will be SUPERSEDED by a higher-priority channel:
> 
>   _libgcc_mutex           pkgs/main::_libgcc_mutex-0.1-main --> conda-forge::_libgcc_mutex-0.1-conda_forge
>   _openmp_mutex          pkgs/main::_openmp_mutex-5.1-1_gnu --> conda-forge::_openmp_mutex-4.5-2_gnu
> 
> 
> 
> Downloading and Extracting Packages:
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> Currently, only install, create, list, search, run, info, clean, remove, update, repoquery, activate and deactivate are supported through mamba.
> Currently, only install, create, list, search, run, info, clean, remove, update, repoquery, activate and deactivate are supported through mamba.
> Currently, only install, create, list, search, run, info, clean, remove, update, repoquery, activate and deactivate are supported through mamba.
> Currently, only install, create, list, search, run, info, clean, remove, update, repoquery, activate and deactivate are supported through mamba.
> Currently, only install, create, list, search, run, info, clean, remove, update, repoquery, activate and deactivate are supported through mamba.
> 
> Looking for: []
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> 
> To activate this environment, use
> 
>      $ mamba activate pimenta
> 
> To deactivate an active environment, use
> 
>      $ mamba deactivate
> 
> 
> Looking for: ['cd-hit']
> 
> warning  libmamba Could not parse mod/etag header
> bioconda/linux-64 (check zst)                       Checked  0.1s
> warning  libmamba Could not parse mod/etag header
> bioconda/noarch (check zst)                         Checked  0.1s
> warning  libmamba Could not parse mod/etag header
> pkgs/main/linux-64 (check zst)                     Checked  0.0s
> warning  libmamba Could not parse mod/etag header
> pkgs/main/noarch (check zst)                        Checked  0.0s
> warning  libmamba Could not parse mod/etag header
> pkgs/r/linux-64 (check zst)                         Checked  0.0s
> warning  libmamba Could not parse mod/etag header
> pkgs/r/noarch (check zst)                           Checked  0.0s
> pkgs/r/linux-64                                      1.6MB @  32.4MB/s  0.1s
> pkgs/main/linux-64                                   5.8MB @  82.6MB/s  0.1s
> pkgs/main/noarch                                   702.8kB @   9.7MB/s  0.1s
> pkgs/r/noarch                                        2.1MB @  21.3MB/s  0.0s
> bioconda/linux-64                                    5.3MB @   4.9MB/s  1.1s
> bioconda/noarch                                      5.1MB @   4.3MB/s  1.2s
> Transaction
> 
>   Prefix: /local/home/olivers/miniconda3/envs/pimenta
> 
>   Updating specs:
> 
>    - cd-hit
> 
> 
>   Package          Version  Build       Channel         Size
> ──────────────────────────────────────────────────────────────
>   Install:
> ──────────────────────────────────────────────────────────────
> 
>   + _libgcc_mutex      0.1  main        pkgs/main     Cached
>   + libstdcxx-ng    11.2.0  h1234567_1  pkgs/main     Cached
>   + libgomp         11.2.0  h1234567_1  pkgs/main     Cached
>   + _openmp_mutex      5.1  1_gnu       pkgs/main     Cached
>   + libgcc-ng       11.2.0  h1234567_1  pkgs/main     Cached
>   + zlib            1.2.13  h5eee18b_0  pkgs/main     Cached
>   + cd-hit           4.8.1  h2e03b76_5  bioconda       257kB
> 
>   Summary:
> 
>   Install: 7 packages
> 
>   Total download: 257kB
> 
> ──────────────────────────────────────────────────────────────
> 
> 
> cd-hit                                             257.1kB @   1.5MB/s  0.2s
> 
> Downloading and Extracting Packages:
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> 
> Looking for: ['r-base']
> 
> warning  libmamba Could not parse mod/etag header
> warning  libmamba Could not parse mod/etag header
> pkgs/main/linux-64                                          Using cache
> pkgs/main/noarch                                            Using cache
> pkgs/r/linux-64                                             Using cache
> pkgs/r/noarch                                               Using cache
> conda-forge/noarch                                  13.6MB @  67.2MB/s  0.2s
> conda-forge/linux-64                                32.6MB @ 121.6MB/s  0.3s
> Transaction
> 
>   Prefix: /local/home/olivers/miniconda3/envs/pimenta
> 
>   Updating specs:
> 
>    - r-base
> 
> 
>   Package                           Version  Build                Channel           Size
> ──────────────────────────────────────────────────────────────────────────────────────────
>   Install:
> ──────────────────────────────────────────────────────────────────────────────────────────
> 
>   + ld_impl_linux-64                   2.40  h41732ed_0           conda-forge      705kB
>   + ca-certificates                2024.2.2  hbcca054_0           conda-forge     Cached
>   + graphite2                        1.3.13  h58526e2_1001        conda-forge      105kB
>   + xorg-libxdmcp                     1.1.3  h7f98852_0           conda-forge       19kB
>   + pthread-stubs                       0.4  h36c2ea0_1001        conda-forge        6kB
>   + fribidi                          1.0.10  h36c2ea0_0           conda-forge      114kB
>   + sed                                 4.8  he412f7d_0           conda-forge      271kB
>   + xorg-renderproto                 0.11.1  h7f98852_1002        conda-forge       10kB
>   + xorg-xproto                      7.0.31  h7f98852_1007        conda-forge       75kB
>   + xorg-kbproto                      1.0.7  h7f98852_1002        conda-forge       27kB
>   + c-ares                           1.26.0  hd590300_0           conda-forge      163kB
>   + libev                              4.33  hd590300_2           conda-forge      113kB
>   + ncurses                             6.4  h59595ed_2           conda-forge      884kB
>   + pixman                           0.43.2  h59595ed_0           conda-forge      387kB
>   + libexpat                          2.5.0  hcb278e6_1           conda-forge       78kB
>   + libffi                            3.4.2  h7f98852_5           conda-forge       58kB
>   + openssl                           3.2.1  hd590300_0           conda-forge     Cached
>   + libwebp-base                      1.3.2  hd590300_0           conda-forge      402kB
>   + xorg-libxau                      1.0.11  hd590300_0           conda-forge       14kB
>   + libdeflate                         1.19  hd590300_0           conda-forge       67kB
>   + lerc                              4.0.0  h27087fc_0           conda-forge      282kB
>   + libjpeg-turbo                     3.0.0  hd590300_1           conda-forge      619kB
>   + gettext                          0.21.1  h27087fc_0           conda-forge        4MB
>   + xz                                5.2.6  h166bdaf_0           conda-forge      418kB
>   + make                                4.3  hd18ef5c_1           conda-forge      519kB
>   + libiconv                           1.17  hd590300_2           conda-forge     Cached
>   + libgfortran5                     13.2.0  ha4646dd_5           conda-forge        1MB
>   + libsanitizer                     13.2.0  h7e041cc_5           conda-forge        4MB
>   + keyutils                          1.6.1  h166bdaf_0           conda-forge      118kB
>   + bzip2                             1.0.8  hd590300_5           conda-forge      254kB
>   + xorg-xextproto                    7.3.0  h0b41bf4_1003        conda-forge       30kB
>   + libzlib                          1.2.13  hd590300_5           conda-forge     Cached
>   + libuuid                          2.38.1  h0b41bf4_0           conda-forge       34kB
>   + xorg-libice                       1.1.1  hd590300_0           conda-forge       58kB
>   + icu                                73.2  h59595ed_0           conda-forge     Cached
>   + libedit                    3.1.20191231  he28a2e2_2           conda-forge      124kB
>   + readline                            8.2  h8228510_1           conda-forge      281kB
>   + expat                             2.5.0  hcb278e6_1           conda-forge      137kB
>   + libxcb                             1.15  h0b41bf4_0           conda-forge      384kB
>   + libgfortran-ng                   13.2.0  h69a702a_5           conda-forge       24kB
>   + libnghttp2                       1.58.0  h47da74e_1           conda-forge      632kB
>   + tk                               8.6.13  noxft_h4845f30_101   conda-forge        3MB
>   + pcre2                             10.42  hcad00b1_0           conda-forge        1MB
>   + libpng                           1.6.42  h2797004_0           conda-forge      289kB
>   + zstd                              1.5.5  hfc55251_0           conda-forge      545kB
>   + libssh2                          1.11.0  h0841786_0           conda-forge      271kB
>   + xorg-libsm                        1.2.4  h7391055_0           conda-forge       27kB
>   + krb5                             1.21.2  h659d440_0           conda-forge        1MB
>   + xorg-libx11                       1.8.7  h8ee46fc_0           conda-forge      829kB
>   + libopenblas                      0.3.26  pthreads_h413a1c8_0  conda-forge        6MB
>   + tktable                            2.10  h0c5db8f_5           conda-forge       90kB
>   + bwidget                          1.9.14  ha770c72_1           conda-forge      122kB
>   + libglib                          2.78.4  h783c2da_0           conda-forge        3MB
>   + freetype                         2.12.1  h267a509_2           conda-forge      635kB
>   + libtiff                           4.6.0  ha9c0a0a_2           conda-forge      283kB
>   + libcurl                           8.5.0  hca28451_0           conda-forge      389kB
>   + xorg-libxext                      1.3.4  h0b41bf4_2           conda-forge       50kB
>   + xorg-libxt                        1.3.0  hd590300_1           conda-forge      379kB
>   + xorg-libxrender                  0.9.11  hd590300_0           conda-forge       38kB
>   + libblas                           3.9.0  21_linux64_openblas  conda-forge       15kB
>   + fontconfig                       2.14.2  h14ed4e7_0           conda-forge      272kB
>   + curl                              8.5.0  hca28451_0           conda-forge       95kB
>   + liblapack                         3.9.0  21_linux64_openblas  conda-forge       15kB
>   + _r-mutex                          1.0.1  anacondar_1          conda-forge        4kB
>   + libgcc-devel_linux-64            13.2.0  ha9c7c90_105         conda-forge        3MB
>   + libstdcxx-devel_linux-64         13.2.0  ha9c7c90_105         conda-forge       13MB
>   + kernel-headers_linux-64          2.6.32  he073ed8_17          conda-forge      711kB
>   + font-ttf-dejavu-sans-mono          2.37  hab24e00_0           conda-forge      397kB
>   + font-ttf-inconsolata              3.000  h77eed37_0           conda-forge       97kB
>   + font-ttf-source-code-pro          2.038  h77eed37_0           conda-forge      701kB
>   + font-ttf-ubuntu                    0.83  h77eed37_1           conda-forge        2MB
>   + sysroot_linux-64                   2.12  he073ed8_17          conda-forge       15MB
>   + fonts-conda-forge                     1  0                    conda-forge        4kB
>   + fonts-conda-ecosystem                 1  0                    conda-forge        4kB
>   + binutils_impl_linux-64             2.40  hf600244_0           conda-forge        5MB
>   + cairo                            1.18.0  h3faef2a_0           conda-forge      982kB
>   + gcc_impl_linux-64                13.2.0  h338b0a0_5           conda-forge       53MB
>   + harfbuzz                          8.3.0  h3d44ed6_0           conda-forge        2MB
>   + gfortran_impl_linux-64           13.2.0  h76e1118_5           conda-forge       16MB
>   + gxx_impl_linux-64                13.2.0  h338b0a0_5           conda-forge       14MB
>   + pango                           1.50.14  ha41ecd1_2           conda-forge      444kB
>   + r-base                            4.3.2  hb8ee39d_2           conda-forge       26MB
> 
>   Change:
> ──────────────────────────────────────────────────────────────────────────────────────────
> 
>   - _libgcc_mutex                       0.1  main                 pkgs/main       Cached
>   + _libgcc_mutex                       0.1  conda_forge          conda-forge     Cached
>   - zlib                             1.2.13  h5eee18b_0           pkgs/main       Cached
>   + zlib                             1.2.13  hd590300_5           conda-forge     Cached
> 
>   Upgrade:
> ──────────────────────────────────────────────────────────────────────────────────────────
> 
>   - libstdcxx-ng                     11.2.0  h1234567_1           pkgs/main       Cached
>   + libstdcxx-ng                     13.2.0  h7e041cc_5           conda-forge     Cached
>   - libgomp                          11.2.0  h1234567_1           pkgs/main       Cached
>   + libgomp                          13.2.0  h807b86a_5           conda-forge     Cached
>   - libgcc-ng                        11.2.0  h1234567_1           pkgs/main       Cached
>   + libgcc-ng                        13.2.0  h807b86a_5           conda-forge     Cached
> 
>   Downgrade:
> ──────────────────────────────────────────────────────────────────────────────────────────
> 
>   - _openmp_mutex                       5.1  1_gnu                pkgs/main       Cached
>   + _openmp_mutex                       4.5  2_gnu                conda-forge     Cached
> 
>   Summary:
> 
>   Install: 82 packages
>   Change: 2 packages
>   Upgrade: 3 packages
>   Downgrade: 1 packages
> 
>   Total download: 187MB
> 
> ──────────────────────────────────────────────────────────────────────────────────────────
> 
> 
> graphite2                                          104.7kB @   2.1MB/s  0.1s
> fribidi                                            114.4kB @   2.0MB/s  0.1s
> ld_impl_linux-64                                   704.7kB @  11.2MB/s  0.1s
> pthread-stubs                                        5.6kB @  89.1kB/s  0.1s
> xorg-libxdmcp                                       19.1kB @ 301.4kB/s  0.1s
> libexpat                                            78.0kB @ 845.6kB/s  0.0s
> xorg-libxau                                         14.5kB @ 153.4kB/s  0.0s
> libev                                              112.8kB @   1.2MB/s  0.0s
> libdeflate                                          67.1kB @ 664.3kB/s  0.0s
> keyutils                                           117.8kB @ 960.8kB/s  0.0s
> xorg-libice                                         58.5kB @ 455.7kB/s  0.0s
> gettext                                              4.3MB @  32.8MB/s  0.1s
> libgfortran-ng                                      23.8kB @ 177.7kB/s  0.0s
> libuuid                                             33.6kB @ 231.1kB/s  0.1s
> bwidget                                            122.5kB @ 727.7kB/s  0.0s
> libssh2                                            271.1kB @   1.5MB/s  0.0s
> xorg-libx11                                        828.7kB @   4.6MB/s  0.0s
> libtiff                                            283.2kB @   1.5MB/s  0.0s
> pcre2                                                1.0MB @   5.2MB/s  0.1s
> xorg-libxt                                         379.3kB @   1.9MB/s  0.0s
> fontconfig                                         272.0kB @   1.3MB/s  0.0s
> _r-mutex                                             3.6kB @  16.8kB/s  0.0s
> kernel-headers_linux-64                            710.6kB @   3.1MB/s  0.0s
> fonts-conda-forge                                    4.1kB @  17.5kB/s  0.0s
> cairo                                              982.4kB @   4.0MB/s  0.0s
> font-ttf-source-code-pro                           700.8kB @   2.8MB/s  0.1s
> xorg-xproto                                         74.9kB @ 283.9kB/s  0.0s
> ncurses                                            884.4kB @   3.0MB/s  0.0s
> libwebp-base                                       401.8kB @   1.3MB/s  0.0s
> xz                                                 418.4kB @   1.4MB/s  0.0s
> gfortran_impl_linux-64                              15.8MB @  49.2MB/s  0.1s
> libxcb                                             384.2kB @   1.2MB/s  0.0s
> libedit                                            123.9kB @ 369.5kB/s  0.0s
> libpng                                             289.1kB @ 816.1kB/s  0.0s
> libsanitizer                                         4.1MB @  11.4MB/s  0.1s
> krb5                                                 1.4MB @   3.8MB/s  0.0s
> libglib                                              2.7MB @   7.4MB/s  0.0s
> r-base                                              25.7MB @  68.8MB/s  0.1s
> xorg-libxext                                        50.1kB @ 131.7kB/s  0.0s
> curl                                                94.9kB @ 241.0kB/s  0.0s
> font-ttf-ubuntu                                      1.6MB @   4.1MB/s  0.0s
> xorg-renderproto                                     9.6kB @  22.7kB/s  0.0s
> binutils_impl_linux-64                               5.4MB @  12.7MB/s  0.1s
> pixman                                             386.8kB @ 891.2kB/s  0.0s
> libjpeg-turbo                                      618.6kB @   1.3MB/s  0.0s
> bzip2                                              254.2kB @ 548.4kB/s  0.0s
> expat                                              136.8kB @ 293.2kB/s  0.0s
> gxx_impl_linux-64                                   13.6MB @  28.4MB/s  0.1s
> zstd                                               545.2kB @   1.1MB/s  0.0s
> tktable                                             89.8kB @ 181.2kB/s  0.0s
> xorg-libxrender                                     37.8kB @  75.5kB/s  0.0s
> libstdcxx-devel_linux-64                            13.0MB @  25.6MB/s  0.1s
> libgcc-devel_linux-64                                2.6MB @   4.9MB/s  0.0s
> fonts-conda-ecosystem                                3.7kB @   6.9kB/s  0.0s
> sed                                                270.8kB @ 504.2kB/s  0.0s
> lerc                                               281.8kB @ 519.8kB/s  0.0s
> xorg-xextproto                                      30.3kB @  54.5kB/s  0.0s
> sysroot_linux-64                                    15.1MB @  27.0MB/s  0.1s
> freetype                                           635.0kB @   1.1MB/s  0.0s
> tk                                                   3.3MB @   5.8MB/s  0.0s
> liblapack                                           14.6kB @  25.6kB/s  0.0s
> make                                               518.9kB @ 872.8kB/s  0.0s
> xorg-kbproto                                        27.3kB @  45.6kB/s  0.0s
> xorg-libsm                                          27.4kB @  45.4kB/s  0.0s
> libnghttp2                                         631.9kB @   1.0MB/s  0.0s
> font-ttf-inconsolata                                96.5kB @ 155.7kB/s  0.0s
> c-ares                                             162.7kB @ 256.0kB/s  0.0s
> readline                                           281.5kB @ 442.8kB/s  0.0s
> libblas                                             14.7kB @  22.8kB/s  0.0s
> pango                                              443.6kB @ 682.1kB/s  0.0s
> libcurl                                            389.2kB @ 581.1kB/s  0.0s
> font-ttf-dejavu-sans-mono                          397.4kB @ 589.9kB/s  0.0s
> libgfortran5                                         1.4MB @   2.1MB/s  0.0s
> libopenblas                                          5.6MB @   8.0MB/s  0.1s
> libffi                                              58.3kB @  82.6kB/s  0.0s
> harfbuzz                                             1.5MB @   2.2MB/s  0.0s
> gcc_impl_linux-64                                   53.3MB @  69.3MB/s  0.2s
> 
> Downloading and Extracting Packages:
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> 
> Looking for: ['perl-cgi', 'perl-bioperl', 'perl-cairo', 'perl-statistics-basic', 'perl-json']
> 
> bioconda/linux-64                                           Using cache
> bioconda/noarch                                             Using cache
> pkgs/main/linux-64                                          Using cache
> pkgs/main/noarch                                            Using cache
> pkgs/r/linux-64                                             Using cache
> pkgs/r/noarch                                               Using cache
> Could not solve for environment specs
> The following packages are incompatible
> ├─ libblas is installable and it requires
> │  └─ libopenblas >=0.3.26,<0.3.27.0a0 , which requires
> │     └─ libgfortran5 >=12.3.0 , which requires
> │        └─ libgfortran-ng 13.2.0 , which can be installed;
> ├─ libexpat is installable and it requires
> │  └─ libgcc-ng >=12 , which can be installed;
> ├─ libjpeg-turbo is installable and it requires
> │  └─ jpeg <0.0.0a , which can be installed;
> ├─ perl-bioperl is installable with the potential options
> │  ├─ perl-bioperl 1.7.8 would require
> │  │  └─ perl-bioperl-core 1.7.8.*  with the potential options
> │  │     ├─ perl-bioperl-core 1.7.8 would require
> │  │     │  └─ perl >=5.32.1,<5.33.0a0 *_perl5, which can be installed;
> │  │     └─ perl-bioperl-core 1.7.8 would require
> │  │        └─ perl-db_file, which does not exist (perhaps a missing channel);
> │  ├─ perl-bioperl 1.6.924 would require
> │  │  └─ perl >=5.22.0,<5.23.0 , which does not exist (perhaps a missing channel);
> │  ├─ perl-bioperl 1.6.924 would require
> │  │  └─ perl 5.22.0* , which does not exist (perhaps a missing channel);
> │  ├─ perl-bioperl 1.7.2 would require
> │  │  └─ perl-bioperl-core [1.007002 |1.7.2 ], which requires
> │  │     └─ perl-gd but there are no viable options
> │  │        ├─ perl-gd [2.56|2.68|2.69|2.70|2.71] would require
> │  │        │  └─ libgd [ |>=2.2.4 |>=2.2.5,<2.3.0a0 ] but there are no viable options
> │  │        │     ├─ libgd [2.2.5|2.3.2] would require
> │  │        │     │  └─ jpeg >=9b,<10a , which conflicts with any installable versions previously reported;
> │  │        │     ├─ libgd 2.3.3 would require
> │  │        │     │  └─ jpeg >=9d,<10a , which conflicts with any installable versions previously reported;
> │  │        │     └─ libgd 2.3.3 would require
> │  │        │        └─ jpeg >=9e,<10a , which conflicts with any installable versions previously reported;
> │  │        ├─ perl-gd 2.56 would require
> │  │        │  └─ perl >=5.22.0,<5.23.0 , which does not exist (perhaps a missing channel);
> │  │        ├─ perl-gd 2.56 would require
> │  │        │  └─ perl 5.22.0* , which does not exist (perhaps a missing channel);
> │  │        ├─ perl-gd 2.56 would require
> │  │        │  └─ perl >=5.22.0,<5.22.1.0a0 , which does not exist (perhaps a missing channel);
> │  │        └─ perl-gd [2.74|2.76] would require
> │  │           └─ libgd >=2.3.3,<2.4.0a0 , which cannot be installed (as previously explained);
> │  └─ perl-bioperl 1.7.8 would require
> │     └─ perl-bio-searchio-hmmer, which requires
> │        └─ perl-db_file, which does not exist (perhaps a missing channel);
> ├─ perl-cairo is installable with the potential options
> │  ├─ perl-cairo 1.109 would require
> │  │  └─ perl >=5.32.1,<5.33.0a0 *_perl5, which can be installed;
> │  ├─ perl-cairo 1.106 would require
> │  │  └─ perl 5.22.0* , which does not exist (perhaps a missing channel);
> │  ├─ perl-cairo 1.106 would require
> │  │  └─ cairo >=1.14.12,<1.15.0a0 , which can be installed;
> │  └─ perl-cairo [1.106|1.109] would require
> │     └─ cairo >=1.16.0,<1.17.0a0 , which can be installed;
> ├─ perl-cgi is not installable because there are no viable options
> │  ├─ perl-cgi 4.22 would require
> │  │  └─ perl >=5.22.0,<5.23.0 , which does not exist (perhaps a missing channel);
> │  ├─ perl-cgi 4.22 would require
> │  │  └─ perl 5.22.0* , which does not exist (perhaps a missing channel);
> │  ├─ perl-cgi [4.22|4.40|4.43|4.44] would require
> │  │  └─ perl [>=5.26.2,<5.26.3.0a0 |>=5.26.2,<5.27.0a0 ], which conflicts with any installable versions previously reported;
> │  └─ perl-cgi [4.44|4.54|4.55|4.56] would require
> │     └─ perl-file-temp but there are no viable options
> │        ├─ perl-file-temp 0.2304 would require
> │        │  └─ perl 5.22.0* , which does not exist (perhaps a missing channel);
> │        └─ perl-file-temp 0.2304 would require
> │           └─ perl >=5.26.2,<5.27.0a0 , which conflicts with any installable versions previously reported;
> ├─ perl-statistics-basic is not installable because there are no viable options
> │  ├─ perl-statistics-basic 1.6611 would require
> │  │  └─ perl-number-format but there are no viable options
> │  │     ├─ perl-number-format 1.75 would require
> │  │     │  └─ perl >=5.22.0,<5.23.0 , which does not exist (perhaps a missing channel);
> │  │     ├─ perl-number-format 1.75 would require
> │  │     │  └─ perl 5.22.0* , which does not exist (perhaps a missing channel);
> │  │     ├─ perl-number-format 1.75 would require
> │  │     │  └─ perl [>=5.26.2,<5.26.3.0a0 |>=5.26.2,<5.27.0a0 ], which conflicts with any installable versions previously reported;
> │  │     └─ perl-number-format [1.75|1.76] would require
> │  │        └─ perl-carp but there are no viable options
> │  │           ├─ perl-carp 1.38 would require
> │  │           │  └─ perl 5.22.0* , which does not exist (perhaps a missing channel);
> │  │           ├─ perl-carp 1.38 would require
> │  │           │  └─ perl [>=5.26.2,<5.26.3.0a0 |>=5.26.2,<5.27.0a0 ], which conflicts with any installable versions previously reported;
> │  │           └─ perl-carp 1.38 would require
> │  │              └─ perl-extutils-makemaker but there are no viable options
> │  │                 ├─ perl-extutils-makemaker 6.66 would require
> │  │                 │  └─ perl >=5.22.0,<5.23.0 , which does not exist (perhaps a missing channel);
> │  │                 ├─ perl-extutils-makemaker [6.66|7.24] would require
> │  │                 │  └─ perl 5.22.0* , which does not exist (perhaps a missing channel);
> │  │                 └─ perl-extutils-makemaker [7.24|7.34|7.36] would require
> │  │                    └─ perl [>=5.26.2,<5.26.3.0a0 |>=5.26.2,<5.27.0a0 ], which conflicts with any installable versions previously reported;
> │  ├─ perl-statistics-basic 1.6611 would require
> │  │  └─ perl >=5.22.0,<5.23.0 , which does not exist (perhaps a missing channel);
> │  └─ perl-statistics-basic 1.6611 would require
> │     └─ perl >=5.26.2,<5.27.0a0 , which conflicts with any installable versions previously reported;
> ├─ r-base is installable with the potential options
> │  ├─ r-base 4.3.2 would require
> │  │  └─ cairo >=1.18.0,<2.0a0 , which conflicts with any installable versions previously reported;
> │  ├─ r-base [3.3.1|3.3.2|3.4.1] would require
> │  │  └─ icu 54.* , which does not exist (perhaps a missing channel);
> │  ├─ r-base 3.4.2 would require
> │  │  └─ libgcc-ng 7.2.0.* , which conflicts with any installable versions previously reported;
> │  ├─ r-base 3.4.3 would require
> │  │  └─ libgfortran-ng >=7,<8.0a0 , which conflicts with any installable versions previously reported;
> │  ├─ r-base [3.4.3|3.5.0] would require
> │  │  └─ libopenblas >=0.2.20,<0.2.21.0a0 , which conflicts with any installable versions previously reported;
> │  ├─ r-base [3.5.0|3.5.1|3.5.3|3.6.0|3.6.1] would require
> │  │  └─ libuuid >=1.0.3,<2.0a0 , which can be installed;
> │  └─ r-base [4.2.0|4.3.1] would require
> │     └─ gfortran_linux-64 11.2.0.* , which requires
> │        └─ gfortran_impl_linux-64 11.2.0.* , which requires
> │           └─ libgfortran5 >=11.2.0,<12.0a0 , which conflicts with any installable versions previously reported;
> └─ xorg-libsm is not installable because it requires
>    └─ libuuid >=2.38.1,<3.0a0 , which conflicts with any installable versions previously reported.
> 
> Looking for: ['blast', 'prinseq=0.20.4', 'cutadapt']
> 
> pkgs/main/linux-64                                          Using cache
> pkgs/main/noarch                                            Using cache
> pkgs/r/linux-64                                             Using cache
> pkgs/r/noarch                                               Using cache
> Could not solve for environment specs
> The following packages are incompatible
> ├─ blast does not exist (perhaps a typo or a missing channel);
> ├─ cutadapt does not exist (perhaps a typo or a missing channel);
> └─ prinseq 0.20.4**  does not exist (perhaps a typo or a missing channel).
> 
> Looking for: ['mafft=7.471', 'openpyxl', 'pandas']
> 
> pkgs/main/linux-64                                          Using cache
> pkgs/main/noarch                                            Using cache
> pkgs/r/linux-64                                             Using cache
> pkgs/r/noarch                                               Using cache
> Could not solve for environment specs
> The following package could not be installed
> └─ mafft 7.471**  does not exist (perhaps a typo or a missing channel).
> 
> Looking for: ['taxopy', 'krona']
> 
> pkgs/main/linux-64                                          Using cache
> pkgs/main/noarch                                            Using cache
> pkgs/r/linux-64                                             Using cache
> pkgs/r/noarch                                               Using cache
> Could not solve for environment specs
> The following packages are incompatible
> ├─ krona does not exist (perhaps a typo or a missing channel);
> └─ taxopy does not exist (perhaps a typo or a missing channel).
> bash: ktUpdateTaxonomy.sh: command not found
> install.sh: line 30: cd: scripts/Porechop/: No such file or directory
> make: *** No targets specified and no makefile found.  Stop.

</details>

**Comment by valerievandervorst** [comment]
Hi, 
I fixed the configurations of the channels in install.sh, could you try it again with the updated script?

**Comment by ocstringham** [comment]
Now it finishes the install. Thanks. I will try to test it with data. A suggestion would be to put test data make sure the install works correctly.

**Comment by valerievandervorst** [comment]
Thanks for the suggestion, I have added a test dataset to the repository

**Comment by OndroV** [comment]
Hello, I still get the following error during `bash install.sh` after the transaction for krona & taxopy:

> Linking taxopy-0.14.0-pyhdfd78af_0
>
> Transaction finished
>
> CondaError: Run 'conda init' before 'conda activate'
> 
> install.sh: line 28: ktUpdateTaxonomy.sh: command not found

Do you have any suggestions, please?
